ユーザー検索機能実装
KIT-DiSH/dish pull request #119
Opened 2021-12-02 10:20 UTC by FujimuraKaito

## やってないこと
- 検索結果のユーザーを表示

2021-12-02 12:12 UTC, shou-watanabe requested changes
Appbarにelevationがついてるけどいらないんじゃないかな？

2021-12-02 13:22 UTC, tksx1227 commented on lib/screens/sample_screens/search_screen.dart
> +          height: 40,
ここ60~70ぐらいあってもいい気がする

2021-12-02 13:24 UTC, tksx1227 commented on lib/screens/sample_screens/search_screen.dart
> +        .where("user_name", isEqualTo: searchText)
ここは `user_id` だと思ってたけどどう…?

2021-12-02 13:26 UTC, tksx1227 commented on lib/screens/sample_screens/search_screen.dart
>      return Scaffold(
`Scaffold` は `GestureDetector` で囲んで、適当な場所タップしたらキーボード閉じるようにしたい

2021-12-02 13:30 UTC, FujimuraKaito commented on lib/screens/sample_screens/search_screen.dart
> +        .where("user_name", isEqualTo: searchText)
ぱっと見`user_name`やとおもっとったけど`user_id`やわ
修正します

2021-12-02 13:41 UTC, tksx1227 commented on lib/screens/sample_screens/search_screen.dart
> +                hintText: 'ユーザーを検索',
某太郎氏が言ってたように、「ユーザーをIDで検索する」的な文言の方がよさそう

2021-12-02 13:44 UTC, tksx1227 requested changes
一通り確認済み

そういえば、これ `sample_screen/` に置かれてるから、`screens/` に移動してほしいっす

2021-12-02 13:46 UTC, tksx1227 commented
ボタンタップしたときに出る影みたいなやつって消せる？

2021-12-03 01:28 UTC, tksx1227 approved these changes
_L G T M !!_

2021-12-03 05:02 UTC, shou-watanabe approved these changes
LGTM!

2021-12-03 05:07 UTC, merged