Feature/#5timeline screen
KIT-DiSH/dish pull request #21
Opened 2021-09-08 09:26 UTC by FujimuraKaito

## 現状
- ロジックなど詳細は詰めれていない

2021-09-08 09:53 UTC, shou-watanabe requested changes

2021-09-08 09:53 UTC, shou-watanabe commented on lib/widgets/timeline_screen/insta_list.dart
> +              padding: const EdgeInsets.fromLTRB(16, 8, 16, 8),
EdgeInsets.symmetric(horizontal: 16, vertical: 8)こっちの方が簡潔

2021-09-08 10:24 UTC, tksx1227 commented on lib/widgets/timeline_screen/insta_list.dart
> +  ),
これを１つのウィジェットとして切り離した方がいいと思ふ

2021-09-08 10:27 UTC, tksx1227 commented on lib/widgets/timeline_screen/insta_list.dart
> +}
可読性のために、別ファイルで定義しておいた方がいいかも

2021-09-08 10:43 UTC, tksx1227 commented on lib/widgets/timeline_screen/insta_list.dart
> +                    Column(
文字は左揃えにしたいかも

```
crossAxisAlignment: CrossAxisAlignment.start,
```

2021-09-08 10:53 UTC, tksx1227 commented on lib/widgets/timeline_screen/insta_list.dart
> +              mainAxisAlignment: MainAxisAlignment.spaceBetween,
この `Row` いらないと思ふ

2021-09-08 10:55 UTC, tksx1227 commented on lib/widgets/timeline_screen/insta_list.dart
> +                Row(
この `Row` は取り除いて、中身を上の `Row` の要素に加える

2021-09-08 11:01 UTC, tksx1227 commented on lib/widgets/timeline_screen/insta_list.dart
> +                      ],
ここに下で定義した `Directionality` を追加する

幅を合わせるために、`Column` と `Directionality` の間に `Spacer()` も追加する


↑をやった後の 2nd row の構成はこんな感じになる
```
// 2nd row
Padding(
  child: Row(
    children: [
      Container(),
      SizedBox(),
      Column(),
      Spacer(),
      Directionality(),
    ]
  ),
)
```

2021-09-08 11:03 UTC, tksx1227 commented on lib/widgets/timeline_screen/insta_list.dart
> +            ),
`SizedBox` を削除して `Row` も除去する

2021-09-08 11:14 UTC, tksx1227 commented on lib/widgets/timeline_screen/insta_list.dart
> +            ),
`SizedBox` を削除して `Row` も除去する

2021-09-08 11:18 UTC, tksx1227 requested changes
一通り目は通したはず

１つの投稿を１つのウィジェットと対応させて、`InstaList` では、その投稿ウィジェットを `Column` で列挙するだけっていう構成にした方が綺麗になると思う

2021-09-09 00:32 UTC, FujimuraKaito commented on lib/widgets/timeline_screen/insta_list.dart
> +              mainAxisAlignment: MainAxisAlignment.spaceBetween,
子要素を`space-between`にするために必要な気がする

2021-09-09 00:38 UTC, FujimuraKaito commented on lib/widgets/timeline_screen/insta_list.dart
> +                      ],
たくまの案はSpacerを使って幅を取る感じか

2021-09-09 01:24 UTC, tksx1227 commented on lib/widgets/timeline_screen/insta_list.dart
> +              mainAxisAlignment: MainAxisAlignment.spaceBetween,
これの上か下のどっちがいいか、って話になるんだけど、俺的には下の方が冗長さが無くてスッキリしてると思うんよ

![image](https://user-images.githubusercontent.com/59915788/132606597-8e558123-9848-46a8-9a2a-2a99c19504cf.png)

2021-09-09 01:30 UTC, tksx1227 commented on lib/widgets/timeline_screen/insta_list.dart
> +                      ],
そやね

2列目は全要素が綺麗に横に並んでいるわけだから、１つ１つを `Row` の `children` として並べるだけでいいと思うの

2021-09-09 01:35 UTC, FujimuraKaito commented on lib/widgets/timeline_screen/insta_list.dart
> +                      ],
なるほど．ちょっと一回そっちでコミットするわ

2021-09-09 02:08 UTC, tksx1227 commented on pubspec.yaml
> +  font_awesome_flutter: ^9.0.0
`FontAwesome` 使ってない気がする

2021-09-09 02:42 UTC, tksx1227 reviewed
確認完了

今更だけど、これインスタグラムじゃないからウィジェットの名前も付けなおした方がいいね
あと、最終コミットでは余分なコメントを消してくれるとありがたい

/* 余談 */
恐らく、ユーザーと投稿のサンプルデータは、プロフィール画面用に作ってたやつと共通化した方がいいんだろうけど、若干データ構造違うからこっちは後で調整することにしよう

2021-09-09 02:45 UTC, tksx1227 commented
> １つの投稿を１つのウィジェットと対応させて、InstaList では、その投稿ウィジェットを Column で列挙するだけっていう構成にした方が綺麗になると思う

↑のイメージ

現状は左側の構成になってるから、右側の構成にしたいかも

![image](https://user-images.githubusercontent.com/59915788/132613638-23d20510-3e04-4dcd-803e-c6bbf71eab58.png)

2021-09-12 06:24 UTC, tksx1227 commented on lib/widgets/timeline_screen/insta_list.dart
> +          ),
ここ、PostModel型のデータを丸ごと渡した方が読みやすいと思う

参考↓
```
DishPost(
  postInfo: posts[index],
),
```

2021-09-12 06:27 UTC, tksx1227 commented on lib/widgets/timeline_screen/insta_list.dart
> +      itemBuilder: (context, index) => Column(
`Column` じゃなくて `DishPost` をそのまま書いていいと思う

参考↓
```
return new ListView.builder(
  itemCount: posts.length,
  itemBuilder: (context, index) => DishPost(
    postInfo: posts[index],
  ),
);
```

2021-09-12 06:30 UTC, tksx1227 commented on lib/widgets/timeline_screen/post.dart
> +  });
PostModel型のデータを丸ごと受け取るように変更したら、もっとシンプルに書ける

```
final PostModel postInfo;

DishPost({
  required this.postInfo,
});
```

2021-09-12 06:34 UTC, tksx1227 reviewed
確認完了
気になったところはコメント書いたよ

2021-09-12 20:41 UTC, shou-watanabe commented
@FujimuraKaito
mapは座標で持っといて欲しい

2021-09-13 03:22 UTC, shou-watanabe requested changes

2021-09-13 03:22 UTC, shou-watanabe commented on lib/models/PostModel.dart
> +    map: 'https://amazom.com',
ここを座標
LatLng(double lat, double lng)みたいなデータ構造にして欲しい

2021-09-13 03:25 UTC, FujimuraKaito commented on lib/models/PostModel.dart
> +    map: 'https://amazom.com',
ごめんそこまだ全然変えてなかったわ

2021-09-14 05:05 UTC, tksx1227 approved these changes
_L G T M !!_

2021-09-15 13:04 UTC, shou-watanabe approved these changes
あとは大丈夫です。
LGTM

2021-09-15 13:04 UTC, shwatanap commented on lib/widgets/timeline_screen/image_slider.dart
> +                        if (!favorite)
`favorite = !favorite;`
こっちの方が簡潔

2021-09-15 13:08 UTC, shou-watanabe commented
コンフリクトの解消がなかなかだるそうだけど頑張って

2021-09-16 01:42 UTC, merged