ファイルまわりの作成
KIT-DiSH/dish pull request #4
Opened 2021-08-15 17:08 UTC by shou-watanabe

- lib
  - screens(スクリーンフォルダ)
    - post_screen.dart
  - widgets(パーツフォルダ)
    - review_form.dart
  - configs
    - constant_colors.dart(色の定数保管ファイル)
のようなファイル構造を実装した。

2021-08-15 23:48 UTC, tksx1227 approved these changes
OK

2021-08-16 00:10 UTC, FujimuraKaito commented
確認済み

2021-08-16 01:45 UTC, tksx1227 requested changes
色の指定方法に修正が必要

2021-08-16 01:45 UTC, tksx1227 commented on lib/configs/constant_colors.dart
> +  static const kStarYellowColor = const Color(0xFFD702);
rgb使うとき、`0x`の後に`FF`入れないと正しく動作しないので、3つとも修正する必要あり。

```
// これは無効
Color(0x333333)

// FFを追加する必要がある
Color(0xFF333333)
```

2021-08-16 03:04 UTC, shou-watanabe commented on lib/configs/constant_colors.dart
> +  static const kStarYellowColor = const Color(0xFFD702);
ほんとやありがとう！

2021-08-16 03:12 UTC, tksx1227 approved these changes
変更を確認済み

2021-08-16 03:12 UTC, merged